[package]
name = "volt"
version = "0.1.0"
edition = "2021"
rust-version = "1.64.0"
license = "MIT or Apache-2.0"

[dependencies]
wry = { version = "0.28.3", default-features = false }

[profile.release]
codegen-units = 1
strip = true
lto = true
